### ISSUE TITLE
Need /users route to get list of all users

### ISSUE THREAD

**Issue by harryganz** [dropTHATdatabase/project3#31]
We are going to need a /users route to get a list of all users to be selected from when creating a scavenger hunt @penguyen1 

We can also modify this route to return an array of length 1 with the owners information when sent with an authorization token.

**Comment by harryganz** [comment]
I am going to have to fix this in the readme as well

**Comment by penguyen1** [comment]
on it

**Comment by harryganz** [comment]
#41
