### ISSUE TITLE
Add username to users

### ISSUE THREAD

**Issue by harryganz** [dropTHATdatabase/project3#6]
In the wireframes users have usernames, but this doesn't appear in the database ERD.

**Comment by penguyen1** [comment]
There are no usernames. I'm assuming that each member that signs up will enter their first and last names. So in the wireframes, {user} will be referencing their first name. There are no usernames unless you want to add that option to the wireframes or ERD

**Comment by harryganz** [comment]
Where are we getting the first names from if they don't enter them on sign up and they aren't stored on the database? I thought we could use usernames, but first/last name id also valid. The point is we cannot display information that isn't entered and is not stored.

**Comment by penguyen1** [comment]
im editting the wireframe as we speak. give me 2 minutes.

**Comment by penguyen1** [comment]
wireframes updated

**Comment by penguyen1** [comment]
closed #6
