### ISSUE TITLE
Track wins and losses on database 

### ISSUE THREAD

**Issue by harryganz** [dropTHATdatabase/project3#8]
Wins and losses appear in wireframes, but not in erd 

* What is a win? 
  * The first to finish or finishing at all
* Maybe have record as won - completed - entered

**Comment by penguyen1** [comment]
sure. I only included the record of wins/losses to fill the empty space. I'll change that part

**Comment by harryganz** [comment]
No I like it. This is just an issue to remind me to include it on the DB. I am thinking you can add view elements for entered/complete/wins

**Comment by penguyen1** [comment]
wireframes updated

**Comment by penguyen1** [comment]
closed #8
